### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by GammaGames** [jevakallio/vscode-hacker-typer#16]
When I try to run the command I get the following error:
![image](https://user-images.githubusercontent.com/7832163/45369335-dfde0900-b5a2-11e8-914e-52c8c50cb26b.png)

I'm currently on Pop!_OS 18.04 LTS, and my VSCode info is:
![image](https://user-images.githubusercontent.com/7832163/45369451-2c294900-b5a3-11e8-8367-da5bceaeef5f.png)

**Comment by jevakallio** [comment]
Hey! I had this issue in an earlier 0.0.x versions, but it should work in versions 0.1.0 and above.

Can you check which version of the plugin you have installed?

**Comment by GammaGames** [comment]
# VS Code System Information

## OS Information

| key | value |
|---|---|
| arch | x64 |
| platform | linux |
| type | Linux |
| release | 4.15.0-34-generic |
| EOL | "\\n" |
| endianness | LE |

## Process Information

| key | value |
|---|---|
| arch | x64 |

### versions

| key | value |
|---|---|
| http_parser | 2.7.0 |
| node | 8.9.3 |
| v8 | 6.1.534.41 |
| uv | 1.15.0 |
| zlib | 1.2.11 |
| ares | 1.10.1-DEV |
| modules | 57 |
| nghttp2 | 1.25.0 |
| openssl | 1.0.2n |

### env

| key | value |
|---|---|
| LANG | en_US.UTF-8 |

## VS Code Information

| key | value |
|---|---|
| version | 1.27.2 |

### env

| key | value |
|---|---|
| appName | Visual Studio Code |
| language | en |

### extensions

#### VSCode HackerTyper

- [open in marketplace](https://marketplace.visualstudio.com/items?itemName=jevakallio.vscode-hacker-typer)
- [open in vscode](vscode:extension/jevakallio.vscode-hacker-typer)

| key | value |
|---|---|
| id | jevakallio.vscode-hacker-typer |
| isActive | true |
| name | vscode-hacker-typer |
| version | 0.1.0 |
| displayName | VSCode HackerTyper |
| description | Hacker Typer extension for looking cool while live coding |
| publisher | jevakallio |
| categories | ["Other"] |

**Comment by jevakallio** [comment]
That's odd! I'll have to investigate the root cause, **Works On My Machine** ™️

**Comment by GammaGames** [comment]
Haha yeah, I figured it was one of those situations. I'm not sure what OS you run, but maybe it's a linux issue? Thank you!

**Comment by jevakallio** [comment]
Can you try to install v0.1.1 and try again? I noticed there was a casing issue in one of my imports, which will work on OSX case-insensitive file system, but will very likely fail on a case-sensitive fs.

I haven't tried it on Linux, don't have any VMs on this machine, so if you could give it a shot and report back, that would be great!

**Comment by przemyslawjanpietrzak** [comment]
I have exact the same issue on macos mojave. Plugin was installed today

**Comment by whekman** [comment]
Somehow I have a similar problem, with the "save macro" command.

VS code system info:

Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 6.1.7601

I will try later on today on a different PC (non-work PC) to see if that somehow makes a difference.

**Comment by nodename** [comment]
I have this issue intermittently with the save command as well.
MacOS 10.13.6
VS Code 1.30.1
node 11.6.0
Just installed the extension today.

**Comment by rakz25** [comment]
Not running on my VSCODE

**Comment by rakz25** [comment]
![screen shot 2019-02-27 at 12 08 03 pm](https://user-images.githubusercontent.com/18657776/53477666-2f55ba00-3a9b-11e9-90d5-3e26155b8aea.png)

**Comment by rakz25** [comment]
![hackertyper](https://user-images.githubusercontent.com/18657776/53478709-78a70900-3a9d-11e9-94fd-9ad67aa3f933.gif)

**Comment by tadatuta** [comment]
https://github.com/jevakallio/vscode-hacker-typer/pull/23 fixed the issue for me.

**Comment by kmoser** [comment]
Using version 0.2.1 of nodename.vscode-hacker-typer-fork, I attempted to record a macro and got: `Command 'HackerTyper: Record Macro' resulted in an error (command 'nodename.vscode-hacker-typer-fork.recordMacro' not found)`. I've tried restarting VSCode several times, as well as uninstalling/reinstalling this extension.

VSCode info:
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363 [Windows 10]

**Comment by nodename** [comment]
Perhaps it would be best to discuss issues about the fork at https://github.com/nodename/vscode-hacker-typer/issues .
I will say please have the status bar open (`View -> Appearance -> Show Status Bar`) while you reproduce this issue, and tell me at that issues page what you see. Thanks!
